/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import java.awt.Color;
import java.awt.Container;
import java.awt.Graphics;
import java.awt.Graphics2D;
import java.awt.print.PageFormat;
import java.awt.print.Printable;
import java.awt.print.PrinterException;
import java.awt.print.PrinterJob;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JFrame;



/**
 *
 * @author 91894
 */
public class PrintReceipt extends javax.swing.JFrame {

    /**
     * Creates new form PrintReceipt
     */
    public PrintReceipt() {
        initComponents();
        setDefaultCloseOperation(JFrame.DO_NOTHING_ON_CLOSE);
        getRecords();
        Container c = getContentPane();
        c.setBackground(new Color(0,153,153));
    }
    
    public void getRecords(){
        try{
            Class.forName("org.apache.derby.jdbc.EmbeddedDriver");
            Connection con = DriverManager.getConnection("jdbc:derby://localhost:1527/fees_ms","root","root");
            PreparedStatement pst = con.prepareStatement("select * from fees_details order by reciept_no desc fetch first 1 rows only");
            ResultSet rs = pst.executeQuery();
            rs.next();
            
            lbl_recieptno.setText(rs.getString("reciept_no"));
            lbl_paymentmode.setText(rs.getString("payment_mode"));
            String payment = rs.getString("payment_mode");
            if(payment.equalsIgnoreCase("cash")){
                txt_dd_cheque_upi.setText("");
                lbl_cheque_dd_upi.setText(""); 
                txt_bankname.setText("");
                lbl_bankname.setText("");
            }
            if(payment.equalsIgnoreCase("demand draft")){
                txt_dd_cheque_upi.setText("DD Number:");
                lbl_cheque_dd_upi.setText(rs.getString("dd_no")); 
                txt_bankname.setText("Bank Name:");
                lbl_bankname.setText(rs.getString("bank_name"));
            }
            if(payment.equalsIgnoreCase("credit/ debit card")){
                txt_dd_cheque_upi.setText("");
                lbl_cheque_dd_upi.setText(rs.getString("")); 
                txt_bankname.setText("Bank Name:");
                lbl_bankname.setText(rs.getString("bank_name"));
            }
            if(payment.equalsIgnoreCase("cheque")){
                txt_dd_cheque_upi.setText("Cheque Number:");
                lbl_cheque_dd_upi.setText(rs.getString("cheque_no")); 
                txt_bankname.setText("Bank Name:");
                lbl_bankname.setText(rs.getString("bank_name"));
            }
            if(payment.equalsIgnoreCase("upi")){
                txt_dd_cheque_upi.setText("UPI Trans. ID:");
                lbl_cheque_dd_upi.setText(rs.getString("upi_no")); 
                txt_bankname.setText("Bank Name:");
                lbl_bankname.setText(rs.getString("bank_name"));
            }
            lbl_recievedfrom.setText(rs.getString("student_name"));
            lbl_date.setText(rs.getString("date_of_receipt"));
            lbl_gstin.setText(rs.getString("gstin"));
            year1.setText(rs.getString("year1"));
            year2.setText(rs.getString("year2"));
            lbl_coursename.setText(rs.getString("course_name"));
            lbl_amount.setText(rs.getString("amount"));
            lbl_cgst.setText(rs.getString("cgst"));
            lbl_sgst.setText(rs.getString("sgst"));
            lbl_totalamount.setText(rs.getString("total_amount"));
            lbl_totalinwords.setText(rs.getString("total_in_words"));
            lbl_remark.setText(rs.getString("remark"));
            
        } catch(Exception e){
            e.printStackTrace();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel6 = new javax.swing.JPanel();
        jLabel12 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jPanel11 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel10 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        panel_reciept = new javax.swing.JPanel();
        jPanel12 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jPanel13 = new javax.swing.JPanel();
        lbl_bankname = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lbl_recieptno = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        lbl_cheque_dd_upi = new javax.swing.JLabel();
        txt_paymentmode = new javax.swing.JLabel();
        lbl_paymentmode = new javax.swing.JLabel();
        txt_dd_cheque_upi = new javax.swing.JLabel();
        txt_bankname = new javax.swing.JLabel();
        lbl_amount = new javax.swing.JLabel();
        lbl_gstin = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        lbl_date = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        jSeparator2 = new javax.swing.JSeparator();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        lbl_cgst = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        lbl_coursename = new javax.swing.JLabel();
        jSeparator3 = new javax.swing.JSeparator();
        lbl_sgst = new javax.swing.JLabel();
        lbl_totalinwords = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jSeparator4 = new javax.swing.JSeparator();
        lbl_totalamount = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        lbl_recievedfrom = new javax.swing.JLabel();
        year2 = new javax.swing.JLabel();
        year1 = new javax.swing.JLabel();
        lbl_remark = new javax.swing.JLabel();
        jLabel50 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));
        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel3MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel3MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel3MouseExited(evt);
            }
        });
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/home.png"))); // NOI18N
        jLabel9.setText(" Home");
        jPanel3.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, -1, -1));

        jPanel1.add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 20, 380, 70));

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));
        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel4MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel4MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel4MouseExited(evt);
            }
        });
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/search2.png"))); // NOI18N
        jLabel10.setText(" Search Record");
        jPanel4.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 60));

        jPanel1.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 100, 380, 70));

        jPanel5.setBackground(new java.awt.Color(0, 102, 102));
        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel5MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel5MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel5MouseExited(evt);
            }
        });
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/edit2.png"))); // NOI18N
        jLabel11.setText(" Edit Course");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 60));

        jPanel1.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 380, 70));

        jPanel6.setBackground(new java.awt.Color(0, 102, 102));
        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel6MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel6MouseExited(evt);
            }
        });
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/list.png"))); // NOI18N
        jLabel12.setText(" Course List");
        jPanel6.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 60));

        jPanel1.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 380, 70));

        jPanel8.setBackground(new java.awt.Color(0, 102, 102));
        jPanel8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel8MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel8MouseExited(evt);
            }
        });
        jPanel8.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel14.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/back-button.png"))); // NOI18N
        jLabel14.setText(" Back");
        jPanel8.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 60));

        jPanel1.add(jPanel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 380, 70));

        jPanel9.setBackground(new java.awt.Color(0, 102, 102));
        jPanel9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel9MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel9MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel9MouseExited(evt);
            }
        });
        jPanel9.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/logout.png"))); // NOI18N
        jLabel15.setText(" Logout");
        jPanel9.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 60));

        jPanel1.add(jPanel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 500, 380, 70));

        jPanel11.setBackground(new java.awt.Color(0, 102, 102));
        jPanel11.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel11.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel11MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel11MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel11MouseExited(evt);
            }
        });
        jPanel11.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(255, 255, 255));
        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/printer-.png"))); // NOI18N
        jLabel17.setText(" Print");
        jPanel11.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 60));

        jPanel1.add(jPanel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 660, 380, 70));

        jPanel10.setBackground(new java.awt.Color(0, 102, 102));
        jPanel10.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel10MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel10MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel10MouseExited(evt);
            }
        });
        jPanel10.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel16.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/edit2.png"))); // NOI18N
        jLabel16.setText(" Edit");
        jPanel10.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 60));

        jPanel1.add(jPanel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 580, 380, 70));

        jPanel7.setBackground(new java.awt.Color(0, 102, 102));
        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.white, null, null));
        jPanel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jPanel7MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jPanel7MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jPanel7MouseExited(evt);
            }
        });
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 36)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/my icons/view all record.png"))); // NOI18N
        jLabel13.setText(" View All Record");
        jPanel7.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 4, -1, 60));

        jPanel1.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 180, 380, 70));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 460, 840));

        panel_reciept.setBackground(new java.awt.Color(255, 255, 255));
        panel_reciept.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyIcons/download.png"))); // NOI18N
        jPanel12.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 10, -1, -1));

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel2.setText("TECHNO MAIN SALT LAKE");
        jLabel2.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(0, 0, 0)));
        jPanel12.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 10, -1, -1));

        jLabel3.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        jLabel3.setText("WEST BENGAL");
        jPanel12.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 60, -1, -1));

        jLabel4.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel4.setText("TECHNO INDIA : EM-4/1, Sector V, Bidhannagar, Kolkata, West Bengal 700091");
        jPanel12.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 90, -1, -1));

        panel_reciept.add(jPanel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 0, 1000, 110));

        jPanel13.setBackground(new java.awt.Color(0, 102, 102));
        jPanel13.setForeground(new java.awt.Color(0, 102, 102));
        panel_reciept.add(jPanel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 110, 1020, 8));

        lbl_bankname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_bankname.setForeground(new java.awt.Color(0, 102, 102));
        lbl_bankname.setText("Reciept ");
        panel_reciept.add(lbl_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Reciept No.:       TIGC-");
        panel_reciept.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        lbl_recieptno.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_recieptno.setForeground(new java.awt.Color(0, 102, 102));
        lbl_recieptno.setText("Reciept ");
        panel_reciept.add(lbl_recieptno, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 150, -1, -1));

        jLabel18.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel18.setForeground(new java.awt.Color(0, 102, 102));
        jLabel18.setText("The following payment in the college office for the year:");
        panel_reciept.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 300, -1, -1));

        lbl_cheque_dd_upi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_cheque_dd_upi.setForeground(new java.awt.Color(0, 102, 102));
        lbl_cheque_dd_upi.setText("Reciept ");
        panel_reciept.add(lbl_cheque_dd_upi, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, -1, -1));

        txt_paymentmode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_paymentmode.setForeground(new java.awt.Color(0, 102, 102));
        txt_paymentmode.setText("Payment Mode: ");
        panel_reciept.add(txt_paymentmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 180, -1, -1));

        lbl_paymentmode.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_paymentmode.setForeground(new java.awt.Color(0, 102, 102));
        lbl_paymentmode.setText("Reciept ");
        panel_reciept.add(lbl_paymentmode, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 180, -1, -1));

        txt_dd_cheque_upi.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_dd_cheque_upi.setForeground(new java.awt.Color(0, 102, 102));
        txt_dd_cheque_upi.setText("DD No.:");
        panel_reciept.add(txt_dd_cheque_upi, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        txt_bankname.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_bankname.setForeground(new java.awt.Color(0, 102, 102));
        txt_bankname.setText("Bank Name:");
        panel_reciept.add(txt_bankname, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 240, -1, -1));

        lbl_amount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_amount.setForeground(new java.awt.Color(0, 102, 102));
        lbl_amount.setText("Amount Details");
        panel_reciept.add(lbl_amount, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 380, 190, 20));

        lbl_gstin.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_gstin.setForeground(new java.awt.Color(0, 102, 102));
        lbl_gstin.setText("GSTIN :");
        panel_reciept.add(lbl_gstin, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 180, -1, -1));

        jLabel27.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(0, 102, 102));
        jLabel27.setText("-");
        panel_reciept.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 300, -1, -1));

        jLabel28.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(0, 102, 102));
        jLabel28.setText("Date:");
        panel_reciept.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 150, -1, -1));

        lbl_date.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_date.setForeground(new java.awt.Color(0, 102, 102));
        lbl_date.setText("Bank Name:");
        panel_reciept.add(lbl_date, new org.netbeans.lib.awtextra.AbsoluteConstraints(810, 150, -1, -1));

        jLabel30.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(0, 102, 102));
        jLabel30.setText("GSTIN :");
        panel_reciept.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 180, -1, -1));

        jSeparator1.setForeground(new java.awt.Color(0, 0, 0));
        panel_reciept.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 360, 980, 10));

        jSeparator2.setForeground(new java.awt.Color(0, 0, 0));
        panel_reciept.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 980, 10));

        jLabel31.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(0, 102, 102));
        jLabel31.setText("Recieved From:");
        panel_reciept.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 270, -1, -1));

        jLabel32.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(0, 102, 102));
        jLabel32.setText("Serial No.");
        panel_reciept.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 340, -1, -1));

        jLabel33.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(0, 102, 102));
        jLabel33.setText("Course Name");
        panel_reciept.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 340, -1, -1));

        jLabel34.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(0, 102, 102));
        jLabel34.setText("cgst  -  9%");
        panel_reciept.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 410, -1, -1));

        jLabel35.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(0, 102, 102));
        jLabel35.setText("sgst  -  9% ");
        panel_reciept.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 440, -1, -1));

        jLabel36.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(0, 102, 102));
        jLabel36.setText("1.");
        panel_reciept.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 380, -1, -1));

        lbl_cgst.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_cgst.setForeground(new java.awt.Color(0, 102, 102));
        lbl_cgst.setText("Amount Details");
        panel_reciept.add(lbl_cgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 410, -1, -1));

        jLabel39.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel39.setForeground(new java.awt.Color(0, 102, 102));
        jLabel39.setText("Amount Details in INR");
        panel_reciept.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 340, -1, -1));

        lbl_coursename.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_coursename.setForeground(new java.awt.Color(0, 102, 102));
        lbl_coursename.setText("Coursename");
        panel_reciept.add(lbl_coursename, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 377, 400, 20));

        jSeparator3.setForeground(new java.awt.Color(0, 0, 0));
        panel_reciept.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 610, 230, 10));

        lbl_sgst.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_sgst.setForeground(new java.awt.Color(0, 102, 102));
        lbl_sgst.setText("Amount Details");
        panel_reciept.add(lbl_sgst, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 440, -1, -1));

        lbl_totalinwords.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_totalinwords.setForeground(new java.awt.Color(0, 102, 102));
        lbl_totalinwords.setText("Amount Details");
        panel_reciept.add(lbl_totalinwords, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 510, 580, -1));

        jLabel44.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel44.setForeground(new java.awt.Color(0, 102, 102));
        jLabel44.setText("Total Amount in words:");
        panel_reciept.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 510, -1, -1));

        jSeparator4.setForeground(new java.awt.Color(0, 0, 0));
        panel_reciept.add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(730, 460, 270, 10));

        lbl_totalamount.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_totalamount.setForeground(new java.awt.Color(0, 102, 102));
        lbl_totalamount.setText("Amount Details");
        panel_reciept.add(lbl_totalamount, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 470, -1, -1));

        jLabel47.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel47.setForeground(new java.awt.Color(0, 102, 102));
        jLabel47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/MyIcons/AYUSH SIGN.jpg"))); // NOI18N
        panel_reciept.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 540, -1, 70));

        jLabel48.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel48.setForeground(new java.awt.Color(0, 102, 102));
        jLabel48.setText("Remarks: ");
        panel_reciept.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 590, -1, 20));

        lbl_recievedfrom.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_recievedfrom.setForeground(new java.awt.Color(0, 102, 102));
        lbl_recievedfrom.setText("Bank Name:");
        panel_reciept.add(lbl_recievedfrom, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, -1, -1));

        year2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        year2.setForeground(new java.awt.Color(0, 102, 102));
        year2.setText("2022");
        panel_reciept.add(year2, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 300, -1, -1));

        year1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        year1.setForeground(new java.awt.Color(0, 102, 102));
        year1.setText("2021");
        panel_reciept.add(year1, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 300, -1, -1));

        lbl_remark.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        lbl_remark.setForeground(new java.awt.Color(0, 102, 102));
        lbl_remark.setText("Admin's Signature");
        panel_reciept.add(lbl_remark, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 560, 350, 80));

        jLabel50.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel50.setForeground(new java.awt.Color(0, 102, 102));
        jLabel50.setText("Admin's Signature");
        panel_reciept.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 610, -1, 20));

        getContentPane().add(panel_reciept, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 120, 1020, 660));

        jLabel38.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(255, 255, 255));
        jLabel38.setText("Printed Receipt");
        jLabel38.setBorder(javax.swing.BorderFactory.createMatteBorder(0, 0, 3, 0, new java.awt.Color(255, 255, 255)));
        getContentPane().add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 30, -1, -1));

        setSize(new java.awt.Dimension(1604, 835));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jPanel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseClicked
        // TODO add your handling code here:
        Home home = new Home();
        home.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel3MouseClicked

    private void jPanel3MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseEntered
        // TODO add your handling code here:
        Color color = new Color(0,51,51);
        jPanel3.setBackground(color);
    }//GEN-LAST:event_jPanel3MouseEntered

    private void jPanel3MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel3MouseExited
        // TODO add your handling code here:
        Color color = new Color(0,102,102);
        jPanel3.setBackground(color);
    }//GEN-LAST:event_jPanel3MouseExited

    private void jPanel4MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseEntered
        // TODO add your handling code here:
        Color color = new Color(0,51,51);
        jPanel4.setBackground(color);
    }//GEN-LAST:event_jPanel4MouseEntered

    private void jPanel4MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseExited
        // TODO add your handling code here:
        Color color = new Color(0,102,102);
        jPanel4.setBackground(color);
    }//GEN-LAST:event_jPanel4MouseExited

    private void jPanel5MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseEntered
        // TODO add your handling code here:
        Color color = new Color(0,51,51);
        jPanel5.setBackground(color);
    }//GEN-LAST:event_jPanel5MouseEntered

    private void jPanel5MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseExited
        // TODO add your handling code here:
        Color color = new Color(0,102,102);
        jPanel5.setBackground(color);
    }//GEN-LAST:event_jPanel5MouseExited

    private void jPanel6MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseEntered
        // TODO add your handling code here:
        Color color = new Color(0,51,51);
        jPanel6.setBackground(color);
    }//GEN-LAST:event_jPanel6MouseEntered

    private void jPanel6MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel6MouseExited
        // TODO add your handling code here:
        Color color = new Color(0,102,102);
        jPanel6.setBackground(color);
    }//GEN-LAST:event_jPanel6MouseExited

    private void jPanel7MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseEntered
        // TODO add your handling code here:
        Color color = new Color(0,51,51);
        jPanel7.setBackground(color);
    }//GEN-LAST:event_jPanel7MouseEntered

    private void jPanel7MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseExited
        // TODO add your handling code here:
        Color color = new Color(0,102,102);
        jPanel7.setBackground(color);
    }//GEN-LAST:event_jPanel7MouseExited

    private void jPanel8MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseEntered
        // TODO add your handling code here:
        Color color = new Color(0,51,51);
        jPanel8.setBackground(color);
    }//GEN-LAST:event_jPanel8MouseEntered

    private void jPanel8MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel8MouseExited
        // TODO add your handling code here:
        Color color = new Color(0,102,102);
        jPanel8.setBackground(color);
    }//GEN-LAST:event_jPanel8MouseExited

    private void jPanel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseClicked
        // TODO add your handling code here:
        Login login = new Login();
        login.show();
        this.dispose();
    }//GEN-LAST:event_jPanel9MouseClicked

    private void jPanel9MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseEntered
        // TODO add your handling code here:
        Color color = new Color(0,51,51);
        jPanel9.setBackground(color);
    }//GEN-LAST:event_jPanel9MouseEntered

    private void jPanel9MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel9MouseExited
        // TODO add your handling code here:
        Color color = new Color(0,102,102);
        jPanel9.setBackground(color);
    }//GEN-LAST:event_jPanel9MouseExited

    private void jPanel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseClicked
        // TODO add your handling code here:
        UpdateFeesDetails update = new UpdateFeesDetails();
        update.setVisible(true);
        this.dispose();
        
    }//GEN-LAST:event_jPanel10MouseClicked

    private void jPanel10MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseEntered
        // TODO add your handling code here:
        Color color = new Color(0,51,51);
        jPanel10.setBackground(color);
    }//GEN-LAST:event_jPanel10MouseEntered

    private void jPanel10MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel10MouseExited
        // TODO add your handling code here:
        Color color = new Color(0,102,102);
        jPanel10.setBackground(color);
    }//GEN-LAST:event_jPanel10MouseExited

    private void jPanel11MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseEntered
        // TODO add your handling code here:
        Color color = new Color(0,51,51);
        jPanel11.setBackground(color);
    }//GEN-LAST:event_jPanel11MouseEntered

    private void jPanel11MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseExited
        // TODO add your handling code here:
        Color color = new Color(0,102,102);
        jPanel11.setBackground(color);
    }//GEN-LAST:event_jPanel11MouseExited

    private void jPanel11MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel11MouseClicked
        // TODO add your handling code here:
        PrinterJob job = PrinterJob.getPrinterJob();
            job.setJobName("Print Data");
            
            job.setPrintable(new Printable(){
            public int print(Graphics pg,PageFormat pf, int pageNum){
                    pf.setOrientation(PageFormat.LANDSCAPE);
                 if(pageNum > 0){
                    return Printable.NO_SUCH_PAGE;
                }
                
                Graphics2D g2 = (Graphics2D)pg;
                g2.translate(pf.getImageableX(), pf.getImageableY());
                g2.scale(0.47,0.47);
                
                panel_reciept.print(g2);
         
               
                return Printable.PAGE_EXISTS;
                         
                
            }
    });
            boolean ok = job.printDialog();
        if(ok){
        try{
            
        job.print();
        }
        catch (PrinterException ex){
	ex.printStackTrace();
}
        }
    }//GEN-LAST:event_jPanel11MouseClicked

    private void jPanel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel4MouseClicked
        // TODO add your handling code here:
        SearchRecord search = new SearchRecord();
        search.setVisible(true);
        this.dispose(); 
    }//GEN-LAST:event_jPanel4MouseClicked

    private void jPanel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel7MouseClicked
        // TODO add your handling code here:
        ViewRecord viewrecord = new ViewRecord();
        viewrecord.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_jPanel7MouseClicked

    private void jPanel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jPanel5MouseClicked
        // TODO add your handling code here:
        EditCourse editcourse = new EditCourse();
        editcourse.show();
        this.dispose();
    }//GEN-LAST:event_jPanel5MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PrintReceipt.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PrintReceipt().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel13;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JLabel lbl_amount;
    private javax.swing.JLabel lbl_bankname;
    private javax.swing.JLabel lbl_cgst;
    private javax.swing.JLabel lbl_cheque_dd_upi;
    private javax.swing.JLabel lbl_coursename;
    private javax.swing.JLabel lbl_date;
    private javax.swing.JLabel lbl_gstin;
    private javax.swing.JLabel lbl_paymentmode;
    private javax.swing.JLabel lbl_recieptno;
    private javax.swing.JLabel lbl_recievedfrom;
    private javax.swing.JLabel lbl_remark;
    private javax.swing.JLabel lbl_sgst;
    private javax.swing.JLabel lbl_totalamount;
    private javax.swing.JLabel lbl_totalinwords;
    private javax.swing.JPanel panel_reciept;
    private javax.swing.JLabel txt_bankname;
    private javax.swing.JLabel txt_dd_cheque_upi;
    private javax.swing.JLabel txt_paymentmode;
    private javax.swing.JLabel year1;
    private javax.swing.JLabel year2;
    // End of variables declaration//GEN-END:variables
}
